### ISSUE TITLE
Registration Checklist

### ISSUE THREAD

**Issue by PatrickKan** [HackIllinois/hackthis-site#12]
# Before release
- [x] Apply button on home page
- [x] Change /test-registration endpoint to /registration
- [x] Ensure confirmation and update emails are being sent
- [x] Any phrasing requests fixed in registration
- [x] FAQ
- [x] Terms of service "By clicking submit you agree to our Terms of Service (link as the words "Terms of Service")"

# Okay to be after release
- [ ] Sponsor icon(s)? (Not super sure about this one)
